export const ADD_CHANNEL = 'ADD_CHANNEL';
export const CURRENT_VIDEO_VIEWED = 'CURRENT_VIDEO_VIEWED';
export const FETCHED_CHANNELS = 'FETCHED_CHANNELS';
export const FETCHED_SUGGESTIONS = 'FETCHED_SUGGESTIONS';
export const UPDATE_VIDEO_LIST = 'UPDATE_VIDEO_LIST';
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL';
export const UPDATE_CURRENT_CHANNEL = 'UPDATE_CURRENT_CHANNEL';